# navigation.icon: i-lucide-book-open
# items:
#   - title: Mykorrhizasvampar
#     path: /docs/1.Mykorrhizasvampar
#     children:
#       - title: Välj Miljö
#         path: /docs/1.Mykorrhizasvampar/1.Välj Miljö
#       - title: Another Topic
#         path: /docs/1.Mykorrhizasvampar/2.AnotherTopic
#   - title: Skogskötsel
#     path: /docs/2.Skogskötsel
#     children:
#       - title: Skogens historik
#         path: /docs/2.Skogskötsel/1.Skogens historik