- title: Inga åtgärder
  path: /skogsskotsel/frameworks/naturskydd
- title: Trakthygge
  path: /skogsskotsel/frameworks/trakthygge
- title: Luckhuggning
  path: /skogsskotsel/frameworks/luckhuggning
- title: Överhållen skärm
  path: /skogsskotsel/frameworks/skarmtrad
- title: Blädning
  path: /skogsskotsel/frameworks/bladning
